### ISSUE TITLE
Full documentation

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#11]
### Feature Description

RTFM

### Use Case

We want to maintain at a minimum the level of documentation standards begun in aicsimageio.

### Solution

Bring docs over from aicsimageio, rewrite as necessary.  First version, probably the api/examples will be similar but the installation will be different.

### Alternatives

Rewrite from scratch?

**Comment by tlambert03** [comment]
ping on this one.  While full documentation would be ideal, even just a minimal readme showing how this library is expected to be used (for those coming from aicsimageio) would be great

**Comment by toloudis** [comment]
> ping on this one. While full documentation would be ideal, even just a minimal readme showing how this library is expected to be used (for those coming from aicsimageio) would be great

See #16 which I think fully addresses this.    At this point the API hasn't changed so most of the code migration would be to change how you install it, and change `AICSImage` to `BioImage`
