### ISSUE TITLE
Plan to keep up with aicsimageio maintenance updates

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#12]
### Feature Description

during this interim period before bioio is ready for release, there could be updates in aicsimageio that get things out of sync.  How will we keep things in sync till we are ready to release?    
See https://github.com/bioio-devs/bioio/pull/9#pullrequestreview-1539680915

I am not proposing a specific strategy but we should at least consider how to deal with this.

**Comment by SeanLeRoy** [comment]
I was thinking soon before bioio is officially released we would take a look back over the recent commits to aicsimageio and see what needs to be added where.

**Comment by evamaxfield** [comment]
This is one where I would love to join a call sometime and chat just to stay updated.

**Comment by toloudis** [comment]
This ticket is just about wanting bioio to start off with the latest and greatest implementations from aicsimageio. 

In theory, once bioio has its first release, aicsimageio goes into full maintenance mode - bugfixes only.  

@SeanLeRoy or @BrianWhitneyAI can correct me if I'm wrong, but I think the plan is to do one more aicsimageio release with the latest stuff,  then remove Python 3.8 support, update some dependencies (dask and...?), and release one more aicsimageio after that.

**Comment by SeanLeRoy** [comment]
@toloudis @evamaxfield
As of this moment in time `bioio` & all the plug-ins have all the features/bugfixes that `aicsimageio
