### ISSUE TITLE
Consider a public plugin registry

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#17]
### Feature Description

Idea: If we encourage community development of plugins, it would be nice to have a registry of plugins.

### Use Case

How will users find plugins for file formats they are interested in?

### Solution

As a minimum, we could add a link to the list of bioio-devs repos in the documentation (or even a python method that lists them as strings!)
Documentation of bioio could suggest ways for users to find plugins they are interested in.

### Alternatives

A registry of all plugins (e.g. searching pypi for bioio_*).  Napari is an example of having a big infrastructure for managing community plugin contributions in a Python project. (Probably bigger than what we need)
Or a registry of "blessed" plugins?

**Comment by SeanLeRoy** [comment]
>Or a registry of "blessed" plugins?

I thought this was the idea for now until we see major development on plug-ins. See [this table](https://bioio-devs.github.io/bioio/OVERVIEW.html#id1) for what I interpreted that as.

**Comment by toloudis** [comment]
> > Or a registry of "blessed" plugins?
> 
That table does pretty well cover it.  I am just anticipating how we might handle third party readers that might become more full-featured or have other advantages, or how to help surface new readers developed by the community.

**Comment by BrianWhitneyAI** [comment]
Let me know if this is acceptable to close @toloudis @evamaxfield

**Comment by evamaxfield** [comment]
Seems good to me for now! The only other easy way to potentially make a registry in the case that others create plugins is to simply inform people in the cookiecutter repo to add a repo-tag of "py-bioio-plugin" since it's easy to simply store a link to GitHub search of a repo tag in the README.

**Comment by BrianWhitneyAI** [comment]
Closing this then! If more info is needed lets open it as a new issue.
