### ISSUE TITLE
Improve error message on UnsupportedFileFormatError

### ISSUE THREAD

**Issue by tlambert03** [bioio-devs/bioio#27]
### Describe the Bug

`UnsupportedFileFormatError` not useful

```python
im = bioio.BioImage('some.nd2')
```

```python
File ~/miniforge3/envs/chunglab/lib/python3.11/site-packages/bioio/bio_image.py:171, in BioImage.determine_reader(image, fs_kwargs, **kwargs)
    168 # If we haven't hit anything yet, we likely don't support this file / object
    169 # with the current plugins installed
    170 image_type = str(type(image))
--> 171 raise biob.exceptions.UnsupportedFileFormatError(
    172     "BioImage",
    173     image_type,
    174     msg_extra=(
    175         "You may need to install an extra format dependency. "
    176         "See bioio README for list of some known plugins."
    177     ),
    178 )

UnsupportedFileFormatError: BioImage does not support the image: '<class 'str'>'. 
You may need to install an extra format dependency. 
See bioio README for list of some known plugins.

```

### Expected Behavior

1.  ~The type is shown incorrectly `image_type = str(type(image))` is very likely to simply show `'<class 'str'>'` which is unlikely to help the user~ .... looks like this is fixed in main
2.  The bioio README doesn't have a list of known plugins
3. It would be nice to have an in-library awareness of known plugins.  that is, if you're going to be maintaining a list in a README somewhere, you might as well put that in that code too to suggest a specific plugin to install.

### Environment

-   OS Version: _[e.g. macOS 11.3.1]_
-   bioio Version: _[e.g. 0.5.0]_

**Comment by SeanLeRoy** [comment]
#16 should fix your second suggestion.

As for your third suggestion, I've been personally on the fence about this since I'm unsure how we'd like to go about choosing the best suggestion to make to users when multiple plug-ins support the same file format. Perhaps we could just return them all

**Comment by tlambert03** [comment]
Definitely, all is better than none (particularly when most cases will be one, and the rare case will be only 2 or 3?)

**Comment by BrianWhitneyAI** [comment]
Will #62 resolve this?

**Comment by evamaxfield** [comment]
I think there are a few things to try before closing this out.

1. When we report that we think the file isn't supported we should dump the list of plugins currently installed. Not all the extensions but the plugins. This should be a relatively short list and an easy way to alert someone if they forgot to install a plugin before trying to read (I forget dependencies a decent amount of the time).

2. We should link them to the registry table in #62 as a part of the error message. Example: please review our list of known plugins to see if there is a plugin that supports your file.

3. If all else fails, we should prompt them to run something like `determine_plugin(file, debug=True)` and link them to the bug report page in the case that they do have the plugin installed (and or they have tried installing a new one), which does the things you have laid out in #26. That is, dumps the list of plugin information and dumps the order in which plugins were tested and the reason for failure.

**Comment by evamaxfield** [comment]
I see this as: "this is the single entry point to using BioIO and if we fail here we should try everything we can to assist them, or tell them to alert us" and if that means a very long error message. So be it haha

**Comment by BrianWhitneyAI** [comment]
> I think there are a few things to try before closing this out.
> 
> 1. When we report that we think the file isn't supported we should dump the list of plugins currently installed. Not all the extensions but the plugins. This should be a relatively short list and an easy way to alert someone if they forgot to install a plugin before trying to read (I forget dependencies a decent amount of the time).
> 2. We should link them to the registry table in [feature/plugin-registry #62](https://github.com/bioio-devs/bioio/pull/62) as a part of the error message. Example: please review our list of known plugins to see if there is a plugin that supports your file.
> 3. If all else fails, we should prompt them to run something like `determine_plugin(file, debug=True)` and link them to the bug report page in the case that they do have the plugin installed (and or they have tried installing a new one), which does the things you have laid out in [Surface more information during reader/plugin selection #26](https://github.com/bioio-devs/bioio/issues/26). That is, dumps the list of plugin information and dumps the order in which plugins were tested and the reason for failure.

I have added [6ae38f3](https://github.com/bioio-devs/bioio/pull/63/commits/6ae38f3f927723b0065b8380072e540d0cd0f7eb). I see this as a bare minimum so let me know if additional context is needed for this.

**Comment by evamaxfield** [comment]
Looks good as a first pass! Thanks so much!

**Comment by fionaEyoung** [comment]
> I see this as: "this is the single entry point to using BioIO and if we fail here we should try everything we can to assist them, or tell them to alert us" and if that means a very long error message. So be it haha

I agree with this, and the error handling is still somewhat unsatisfactory I fear. Something as simple as the file not existing results in this misleading `UnsupportedFileFormatError`, as the reader errors are caught in this catch-all https://github.com/bioio-devs/bioio/blob/1bee8d167a2c3fcfe2dfc563cac20cebeeb18f19/bioio/bio_image.py#L350-L360 
resulting in a buried warning like this:

```
WARNING : Dummy-1 : Exclusive reader attempt failed. reader=Reader image=PosixPath('Users/.../image.tiff') error=('file', 'local'):///Users/.../image.tiff
```

followed by a long `UnsupportedFileFormatError` traceback.

As a sidenote, many plugins simply call their reader class `Reader` so the warning doesn't help identify the plugin involved.

For now it's up to the user to do their own file checks before trying `BioImage(fpath, ...)`
