### ISSUE TITLE
Add ArrayLikeReader

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#39]
### Feature Description

BioImage should be able to wrap an already in memory numpy array.

### Use Case

This previously existed in aicsimageio and some scientists have asked for it.

### Solution

Bring this implementation over:
https://github.com/AllenCellModeling/aicsimageio/blob/main/aicsimageio/readers/array_like_reader.py
Add it to bioio.
Plugin selection can check for arraylike first and apply this reader if a numpy array is passed in instead of a path/url etc.

**Comment by BrianWhitneyAI** [comment]
Some clarifying questions:

1) This would not be creating a new reader plugin this would be adding the arraylike reader to the bioio repository 
2) The check would most likely occur [here](https://github.com/bioio-devs/bioio/blob/3b3dc54789263295b53a7df2f71a0a54c038a0e4/bioio/bio_image.py#L151)
