### ISSUE TITLE
Centralized guess dim order 

### ISSUE THREAD

**Issue by BrianWhitneyAI** [bioio-devs/bioio#49]
Just curious. I think this may be the third time we have this code in multiple places? (Base) TiffReader, this one, and somewhere else?? Should we centralize this to a standard function that is called `guess_dims_from_shape` that all of these different Readers call?

_Originally posted by @evamaxfield in https://github.com/bioio-devs/bioio/pull/47#discussion_r1666999390_

**Comment by BrianWhitneyAI** [comment]
Looking back on this is this still something we want to do? I think I am against it because there is a certain precedent that comes with the specific file types where the logic is present that is not necessarily generalized. @evamaxfield

**Comment by evamaxfield** [comment]
I just did a quick search through all the plugins. The guess_dim_orders are all different throughout. Closing!
