### ISSUE TITLE
Migration document from aicsimageio

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#5]
### Feature Description

Create a migration document that shows a recipe for switching over from aicsimageio for people who are ready to do so.

### Use Case

We wish to encourage users to switch to the new system. Such a document would also allow us to easily see where are the difficult parts of this migration.

### Solution

```
1. Install separate reader packages.
2. Update import statements and replace AICSImage with BioImage.
3. Profit! 
```

**Comment by SeanLeRoy** [comment]
A snippet somewhere in this explaining why this change happened might be useful too
