### ISSUE TITLE
remove zarr<2.18.0 constraint

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio#53]
### Feature Description

Tests were failing on #48 because of more recent zarr versions so I had to pin to pre-2.18.  Ideally this should not be a constraint.

### Use Case

We want to be able to take advantage of all the fixes and improvements that come with new zarr releases!

### Solution

Unpin to zarr<3 and eventually allow v3 support too

**Comment by SeanLeRoy** [comment]
Resolved as of now
