### ISSUE TITLE
Plugin Reader Metadata Does Not Standardize Supported Suffixes

### ISSUE THREAD

**Issue by evamaxfield** [bioio-devs/bioio#56]
### Describe the Bug

Found while working on understanding #55 (#54): Some reader metadata files include leading `.` while others do not. This results in our plugin cache having duplicate entries for what is the same suffix.

For example:

* [bioio-ome-tiff](https://github.com/bioio-devs/bioio-ome-tiff/blob/main/bioio_ome_tiff/reader_metadata.py#L20) INCLUDES a leading period
* [bioio-tiff-glob](https://github.com/bioio-devs/bioio-tiff-glob/blob/main/bioio_tiff_glob/reader_metadata.py#L20) INCLUDES a leading period
* [bioio-ome-zarr](https://github.com/bioio-devs/bioio-ome-zarr/blob/main/bioio_ome_zarr/reader_metadata.py#L20) INCLUDES a leading period

No other readers do however.

* [bioio-tifffile](https://github.com/bioio-devs/bioio-tifffile/blob/main/bioio_tifffile/reader_metadata.py#L20)
* [bioio-imageio](https://github.com/bioio-devs/bioio-imageio/blob/main/bioio_imageio/reader_metadata.py#L20)
* etc.

This causes problems during plugin parsing and organization on the `bioio` side because we create our plugin cache based off of the suffixes. If `bioio-tifffile` and `bioio-ome-tiff` both list `tiff` and `.tiff` respectively in their reader_metadata files. That will create two entries rather than one.

### Expected Behavior

I don't think we can always trust that the plugin authors will follow a standard regarding some arbitrary suffix information. Instead we can do some minor clean up during plugin cache creation time to either always remove or always add a leading period.

### Reproduction

Add print statements checking for leading "." during plugin cache creation ([my debug prints](https://github.com/bioio-devs/bioio/blob/ae6949e25c0a17da399afb01f01c72f27f20603b/bioio/plugins.py#L226)), or, print the plugin cache after creation and look for duplicate suffixes.

**Comment by evamaxfield** [comment]
Actually, I see that this was already being done at `determine_plugin` time, however since we would still prefer to not have _duplicate_ suffixes in the plugin cache, I think it's still better to handle this earlier in the stack.

**Comment by BrianWhitneyAI** [comment]
is this part of https://github.com/bioio-devs/bioio/pull/55

**Comment by evamaxfield** [comment]
Yes I will handle as part of my existing pull request
