### ISSUE TITLE
Reader-specific documentation can be hard to discover

### ISSUE THREAD

**Issue by pgarrison** [bioio-devs/bioio#60]
### Feature Description

The `bioio` repository should point to/link to/reference/copy documentation for the readers.

### Use Case

The `bioio-ome-zarr` reader has the following documentation in its README.md:
> If using an `s3://` path to access a public S3 bucket, the `BioImage` constructor must be given a dictionary with `anon: True` in the `fs_kwargs` argument.

This may be relevant to many readers, but consistency and coordination across all readers is challenging due to the many repositories.

### Solution

1. Option 1: `bioio`'s README could link to `bioio-ome-zarr`'s README
2. Option 2: the text from the `bioio-ome-zarr` example above could be copied into `bioio`'s README
3. Option 3: Centralize all documentation by updating all readers' READMEs to say "Documentation for this repository lives at https://github.com/bioio-devs/bioio/" and adding a section for each reader to the central `bioio` README

**Comment by BrianWhitneyAI** [comment]
The repositories for each of the readers are linked in the bioio docs[ here](https://bioio-devs.github.io/bioio/OVERVIEW.html#:~:text=outside%20of%20these%3A-,Package,-Supported%20File%20Types). There has been some talk about adding a manifest of plugins to bioio [here](https://github.com/bioio-devs/bioio/issues/17). Would adding a basic registery of the repositories to the README be enough to resolve this issue? @pgarrison
