### ISSUE TITLE
Plans to drop py39 and add py312

### ISSUE THREAD

**Issue by evamaxfield** [bioio-devs/bioio#65]
Do we have any clear plan for dropping py39 support and adding py312 support? We previously tried to follow the NumPy / SciPy supported versions schedule relatively closely: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

**Comment by evamaxfield** [comment]
I dont know why I thought we didn't support py312.... I just installed locally with no-cache-dir enabled so 🤷‍♀️ I still think we should drop py39 and add py313 in October when 3.13 releases: https://peps.python.org/pep-0719/#release-schedule

cc @toloudis

**Comment by toloudis** [comment]
I think it's about a year too early to talk about dropping 3.9!

**Comment by evamaxfield** [comment]
Fair enough, 3.9 is still heavily used, but I would somewhat expect new versions of numpy + dask + likely tifffile to not support 3.9 already: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

So we should just be aware of that.
